### ISSUE TITLE
Private contract values can be updated by everyone

### ISSUE THREAD

**Issue by Leo-Besancon** [jpmorganchase/quorum-examples#122]
Hi, I set up the example described in the 7Nodes documentation, with node 1 deploying a contact giving a private access to node 7.
When I first set a new value (4) from node 1, and call `private.get()` from all nodes, I get the correct values : 4 from nodes 1 and 7, and 0 from node 4.

Also, `eth.getCode(address)` shows that node 4 does not have access to the contract's code.

However, if I set a new value (8) from node 4 (using the same command: `private.set(8,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});`), then node 1 has value 4 and node 4 has value 0, which is normal, but node 7 reads 8.

That means that node 4 is able to update the value of the private contract for one or more nodes as long has he knows the address and ABI of the contract. If I understand the docs correctly, this shouldn't happen?

**Comment by prd-fox** [comment]
Currently what you are seeing is 'expected' behaviour. Anyone can update the contract providing they have the contract address and valid ABI.

I quote 'expected' because this can cause issues. The current solution is enable access controls within the contract itself based ethereum addresses instead of PrivateTransactionManager keys.

This is something we are working on.

Also see https://github.com/jpmorganchase/quorum/issues/126
