### ISSUE TITLE
Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory

### ISSUE THREAD

**Issue by princesinha19** [jpmorganchase/quorum-examples#130]
I want to run Quorum locally so I have installed Quorum and constellation locally for that I followed the step.
https://github.com/jpmorganchase/quorum/wiki/Getting-Set-Up

Then, I tried to run 7nodes example locally. 
I have successfully run the command "raft-init.sh". Here is the output:-
![quorum raft succesful](https://user-images.githubusercontent.com/28489437/47549341-62374800-d919-11e8-8ce8-a73031d89b59.png)
After that, I followed the next step. To run the command "geth attach qdata/dd1/geth.ipc" in new terminal but it gives the error:
**Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory**

So, How can I run 7nodes example locally?

**Comment by SatpalSandhu61** [comment]
A couple of things to check:
1) Does the ipc file exist (qdata/dd1/geth.ipc)?
2) Are there any errors in the log file (qdata/logs/1.log)?

If the node hasn't started correctly, or has died then the ipc file won't exist and you won't be able to connect to the node.

**Comment by princesinha19** [comment]
@SatpalSandhu61

> 1. Does the ipc file exist (qdata/dd1/geth.ipc)?

No, ipc file doesn't create/exists if I run it locally. If I run it through vagrant then, in that case, ipc file got created.

> 2. Are there any errors in the log file (qdata/logs/1.log)?

Log file contains the following:-
```
nohup: appending output to 'nohup.out'
flag provided but not defined: -raft
```

> If the node hasn't started correctly or has died then the ipc file won't exist and you won't be able to connect to the node.

I have installed the Quorum and constellation. The raft-start.sh is also successful then, what should I do to check the node has started correctly or died?

**Comment by SatpalSandhu61** [comment]
If there is no error in the log file then geth should be running ok. You can double check with:
```
ps -ef | grep -i geth
```
In which case, the geth.ipc file should exist. Is it possible you're in the wrong location for the qdata directory?
Are you in the 7nodes directory when you're running "geth attach qdata/dd1/geth.ipc"?
Can you paste the results from:
```
pwd
ls -ltr qdata/dd1
geth attach qdata/dd1/geth.ipc
```

**Comment by princesinha19** [comment]
Yes @SatpalSandhu61 this is the result of

> pwd
> ls -ltr qdata/dd1
> geth attach qdata/dd1/geth.ipc

![7nodes qdata](https://user-images.githubusercontent.com/28489437/47561218-4b541e00-d938-11e8-923b-a38200148137.png)

> output ps -ef | grep -i geth

`prince    4153  2228  0 15:59 pts/18   00:00:00 grep --color=auto -i geth`

**Comment by princesinha19** [comment]
**constellation is also working fine I guess**. This is the output of constellation1.log:-
![constellation](https://user-images.githubusercontent.com/28489437/47561341-af76e200-d938-11e8-9720-39d9a4c26417.png)

**Comment by ayushkaul95** [comment]
@SatpalSandhu61 @princesinha19 
I think the problem is with this log: "flag provided but not defined: -raft".
This is 1.log:
![log1](https://user-images.githubusercontent.com/24712560/47561866-34163000-d93a-11e8-8af0-f6d9246b22b0.png)
No such log in:
![log2](https://user-images.githubusercontent.com/24712560/47561867-34163000-d93a-11e8-831a-8c9c5b6b10e7.png)

**Comment by AyushKaul** [comment]
@SatpalSandhu61 @princesinha19
I think the problem is with this log: "flag provided but not defined: -raft".
This is 1.log in my local machine vs vagrant environment:
![log1](https://user-images.githubusercontent.com/24712560/47562282-9de30980-d93b-11e8-8afa-738ef45848b5.png)
![log2](https://user-images.githubusercontent.com/24712560/47562295-aafff880-d93b-11e8-8355-846f6ddb2a89.png)

**Comment by SatpalSandhu61** [comment]
@princesinha19, ok - so it does look like your geth processes are not starting up.
@ayushkaul95 may be correct, but I'm not sure at the moment why it's complaining about the --raft flag. The command line options all look correct to me.
What version of quorum are you running?
Is it possible you have an old version of 'geth' on your path that is being picked up?

**Comment by princesinha19** [comment]
@SatpalSandhu61 @ayushkaul95 
Thanks for your clarifications. Maybe @ayushkaul95, you are right.

>  What version of quorum are you running?

VERSION
   1.7.2-stable-0d0c507a

**Comment by SatpalSandhu61** [comment]
That's the ethereum version that quorum is using.
I meant which version of quorum have you checked out and built?
I'd suggest checking out and building the latest version (v2.1.1), and also ensure you have a recent checkout of quorum-examples/master.

**Comment by princesinha19** [comment]
@SatpalSandhu61 From where i can get Quorum version (v2.1.1).  Can you please share the link.

**Comment by SatpalSandhu61** [comment]
Actually, it looks like you do have the latest quorum version. If you want to do a fresh checkout here are the repo's:
Quorum: https://github.com/jpmorganchase/quorum/releases
Quorum-examples: https://github.com/jpmorganchase/quorum-examples
I believe the issue may be that you are picking up a native geth, rather than Quorum.
Can you check that the Quorum binary is on the path? (Try 'which geth' before you execute the raft-init/raft-start commands).

**Comment by princesinha19** [comment]
@SatpalSandhu61 Yes, I have latest Quorum & Quorum-examples.
> Can you check that the Quorum binary is on the path? (Try 'which geth' before you execute the raft-init/raft-start commands).

![which geth](https://user-images.githubusercontent.com/28489437/47611482-a434cb00-da8c-11e8-8ad9-dcd7fea3d7b6.png)

**Comment by princesinha19** [comment]
@SatpalSandhu61 @ayushkaul95 Thanks.

> Can you check that the Quorum binary is on the path? (Try 'which geth' before you execute the raft-init/raft-start commands).

@SatpalSandhu61 You was right. This was the problem. 

I solved it by setting the geth PATH as:- **/home/prince/quorum/build/bin/geth**
Before that, it was taking the ethereum geth as geth Path. That's why geth.ipc file doesn't get created.

**Comment by tanmoyAtb** [comment]
Hello, I have been trying to get quorum running using docker,
I have the same error,

`Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory`

I have geth installed in my system using `brew`

**Comment by TummanapallyAnuraag** [comment]
@princesinha19 
> I solved it by setting the geth PATH as:- /home/prince/quorum/build/bin/geth

How to set geth PATH to `/home/anuraag/Documents/quorum/build/bin/geth`


@tamoy12
I too had installed `ethereum` package from `apt-get`, I guess that is the one causing the problem.

because when i run `which geth`, i get 

`/usr/bin/geth` as output.

**Comment by diegoclair** [comment]
Hi guys,

I'm having the same problem, but I only trying the follow comand: `geth attach`
and I got "**Fatal: Unable to attach to remote geth: dial unix /home/diego/.ethereum/geth.ipc: connect: no such file or directory**"

I'm use the azure vm, connected by ssh from my WSL on windows.

I'm not an expert on the subject, either english, so if someone could help me wrinting step by sted I'll be so greteful.

Some informations:

![image](https://user-images.githubusercontent.com/35784268/60749976-4d1aba80-9f78-11e9-9de1-5d73e921c432.png)
![image](https://user-images.githubusercontent.com/35784268/60749986-76d3e180-9f78-11e9-81c8-386276602d13.png)
![image](https://user-images.githubusercontent.com/35784268/60750008-c1555e00-9f78-11e9-83e3-a0d6fa67bf24.png)

**Comment by SatpalSandhu61** [comment]
Please don't raise questions on closed tickets. If you have a quorum issue then raise a new ticket. In this case, where you are asking a question rather than facing a genuine Quorum issue, I refer you to our Slack channel. There is a large community on there who can answer your questions and help you out. You can join the channel by clicking on the link [here](https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/).

In your case, the geth version you are executing is actually the standard Ethereum executable. It is not Quorum. You need to follow the instructions on our wiki to build or download Quorum.
The best way for you to get started is to run the [quorum-examples](https://github.com/jpmorganchase/quorum-examples).

**Comment by diegoclair** [comment]
Sorry about that
