### ISSUE TITLE
unable to find Cakeshop war file using CAKESHOP_JAR envvar, or using $PWD/cakeshop/cakeshop.war

### ISSUE THREAD

**Issue by ghost** [jpmorganchase/quorum-examples#232]
cakeshop.war file is not available under folder quorum-examples/7nodes/cakeshop/cakeshop.war

#### System information
Geth version:
Version: 1.9.7-stable
Git Commit: 80564d5f26d464e9e5c99e74338d1cf0a8428493
Git Commit Date: 20200509
Quorum Version: 2.6.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.14.2
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go

OS & Version: OSX

Environment: host os

#### Expected behavior
Cakeshop should start post executing cakeshop-init.sh then cakeshop-start.sh.

#### Actual behavior
Error

```
MacBook-Pro 7nodes % ./cakeshop-start.sh
ERROR: unable to find Cakeshop war file using CAKESHOP_JAR envvar, or using /home/vagrant/cakeshop/cakeshop.war
```

**Comment by fixanoid** [comment]
Hi @mrarjunbgupta if you are running locally, the instructions are a bit out of date and will be updated shortly. But if you examine vagrant bootstrapping file, you will see whats missing and whrere to get it: https://github.com/jpmorganchase/quorum-examples/blob/master/vagrant/bootstrap.sh

Thanks.

**Comment by fixanoid** [comment]
An alternative to quorum-examples is quorum-wizard project that you should try as well: https://github.com/jpmorganchase/quorum-wizard

**Comment by ghost** [comment]
Thank you! I have downloaded war file from https://github.com/jpmorganchase/cakeshop and put it under cakeshop folder. Now, it is working fine.

**Comment by mrarjunbgupta** [comment]
@fixanoid I am getting multiple errors while submitting update transaction from UI i.e. I am able invoke get function to get the value but set function is failing from UI because of privateFor parameter (differs from ethereum). I have tried with VAGRANT and LOCAL Quorum version but didn't get success.

**Do you have any sample code which invokes set function from JS file using quorum-js or web3 etc which can be integrated to an UI? If yes, please share.**
