### ISSUE TITLE
7nodes example with docker-compose

### ISSUE THREAD

**Issue by meguimendia** [jpmorganchase/quorum-examples#235]
I'm using ubuntu16.04 and 8GB of ram.
I have installed Docker version 19.03.11, build 42e35e61f3 and docker-compose version 1.25.5, build 8a1c60f6
Then I have cloned the repository and I have tried to do docker-compose up -d, but all my container are in an unhealthy state.
Is there anything that I can try to solve the problem?

**Comment by fixanoid** [comment]
@meguimendia check your container logs and see if you can share them.

**Comment by meguimendia** [comment]
I've got this warning in txmanagers:
![txmanager](https://user-images.githubusercontent.com/36035672/84148387-35d52e80-aa5f-11ea-86d3-4f36fe4a1cb8.png)
![txmanager2](https://user-images.githubusercontent.com/36035672/84148431-48e7fe80-aa5f-11ea-8c25-90630445ded8.png)
And this error in cakeshop:
![cakeshop](https://user-images.githubusercontent.com/36035672/84148553-7634ac80-aa5f-11ea-8856-ff0b95272554.png)
I couldn't found errors in nodes.

And when I tried to go inside the containers I've got this message:

panic: MustNew: Failed to connect to private transaction manager (/qdata/tm/tm.ipc): lstat /qdata/tm/tm.ipc: no such file or directory

goroutine 1 [running]:
github.com/ethereum/go-ethereum/private/privatetransactionmanager.MustNew(0xc00003800f, 0x10, 0xc00003800f)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/privatetransactionmanager/tx_manager.go:108 +0x1de
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0x1344560, 0xe, 0xc0001c9660, 0xc0001c9640)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:20 +0x64

I'm not sure if this cause the unhealthy state or because of the unhealthy state I've got this error.
I don't know if that helps.

**Comment by benjamincburns** [comment]
@fixanoid this problem is really easy to reproduce - just clone the repo and run `docker-compose up`

In my case the nodes die and the transaction manager stays alive. I see `Fatal: Account unlock with HTTP access is forbidden!` in the output immediately before the nodes die.

I'm also seeing errors about failing to enumerate USB devices (I assume these are non-fatal), and some "dial errors"

**Comment by chris-j-h** [comment]
Hi, sounds like there's two different issues being discussed here.

@benjamincburns thanks for raising those, they are fixed in #236.  

@meguimendia I suspect your issue is related to insufficient available memory resulting in the transaction managers being unable to start.  We recommend you configure the Docker daemon with at least 4GB, although ideally as much as you can spare.  
If this still doesn't resolve your issue, try reducing the number of nodes started by docker-compose.  You can do this [manually](https://github.com/jpmorganchase/quorum-examples#reducing-the-number-of-nodes), although I'd recommend using [`quorum-wizard`](https://github.com/jpmorganchase/quorum-wizard).  This is a CLI tool that will allow you to easily start-up 2-7 nodes using docker-compose.  It also updates the 7nodes example scripts so that you can continue to work through the quorum-examples.

I'll close this issue now, please reopen if you continue to have issues.
